name: Cleanup deleted files from dev in main

on:
  workflow_dispatch:
  workflow_call:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Merge dev to main
        run: |
          git pull
          git merge --allow-unrelated-histories $(git commit-tree -p main -m "[Automated] Cleanup" origin/dev^{tree})
      - name: Rename Samples folder
        run: |
          git rm Samples.meta
          git mv Samples Samples~
          git commit --amend --no-edit --allow-empty
      - name: Push
        run: |
          git push
